### ISSUE TITLE
Auto generating API keys using our Application Authentication Endpoint

### ISSUE THREAD

**Issue by mbeauchamp7** [woocommerce/woocommerce-rest-api-docs#104]
I created my wordpress with woo commerce web site. (wordpress 4.7.3, woocommerce 3.0.1)

I'm trying to test the wc-auth endpoint to generate api keys but the endpoint is not even there. In the Wiki it says `v1` and on the website `v2` and there's a bunch of 404 pages in the Wiki.

Could someone tell how can I enable the endpoint `/wc-auth/v2/authorize` please?

**Comment by claudiosanches** [comment]
This repository is not a support channel for the REST API.
Please open issues only for the issues with the REST API documentation.
Thanks.

**Comment by mbeauchamp7** [comment]
Hi, thanks for the quick feedback.

I'm sure if it's the documentation but I followed every step in there and I get a 404 with the `/wc-auth/v2/authorize` endpoint specified in the documentation. Either I missed something or the documentation is unclear.

**Comment by claudiosanches** [comment]
Yes, need to be `/wc-auth/v1/authorize`

**Comment by mikejolley** [comment]
@claudiosanches updating docs?

**Comment by claudiosanches** [comment]
@mikejolley already updated.

**Comment by mbeauchamp7** [comment]
Ahhhh I get a `401` now, thanks!
