### ISSUE TITLE
Woocommerce REST API v2 Brake changes

### ISSUE THREAD

**Issue by ikourfaln** [woocommerce/woocommerce-rest-api-docs#105]
we are doing a migration of an ionic app using Woocommerce REST API v1 (WC v2.6) to Woocommerce REST API v2 (WC v3), so we are are looking for a list of breaking changes and we didn't find anything list those BC !! so please can someone share with us.

**Comment by claudiulodro** [comment]
The easiest way is going to be to take a look at the [v2 API docs](https://woocommerce.github.io/woocommerce-rest-api-docs/). All of the JSON objects' properties are documented, so you should be able to see if you'll have problems.

That being said, WooCommerce 3.0 includes API v1 (in addition to v2), and future version of WooCommerce will also include v1. If v1 is working for you, you can keep using it.

**Comment by ikourfaln** [comment]
@claudiulodro 
thanx for clarifying that.
