### ISSUE TITLE
Webhook request header properties documentation

### ISSUE THREAD

**Issue by mbeauchamp7** [woocommerce/woocommerce-rest-api-docs#106]
In the documentation, the webhooks are spelled like this `X-WC-Webhook-ID` and what we actually receive is `X-Wc-Webhook-Id` camel case version.

Also, there seems to be a missing one, `X-Wc-Webhook-Source`.

**Comment by claudiosanches** [comment]
In WooCommerce are send as `X-WC-Webhook-ID`.
