### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by SkyNeT-ProD** [woocommerce/woocommerce-rest-api-docs#113]
Hey, since the update of the API, I can't create variations using the products endpoint.
So I'm updating my code and using the products/<id>/variations endpoint.

The problem is I can't create a massive number of variations using only one array, I have to $woocommerce->post('products/<id>/variations', $variation) for each variation instead of pushing them all at once using one array.

**Example :**
This is my array :`$variations = [
				[
					'attributes' =>
						[
							[
								'name'   => 'Color',
								'option' => 'Green'
							],
							[
								'name'   => 'Size',
								'option' => 'XXL'
							]
						]
				];`

But let's say I have one more variation for example : `'attributes' =>
						[
							[
								'name'   => 'Color',
								'option' => 'Pink'
							],
							[
								'name'   => 'Size',
								'option' => 'L'
							]
						]`

How can I push them both at once using only one array?
Thank you in advance for your help!

**Comment by claudiosanches** [comment]
This does not sounds like an issue with this documentation, if you have questions with WooCommerce REST API you should use the properly support channel: https://wordpress.org/support/plugin/woocommerce

**Comment by SkyNeT-ProD** [comment]
The documentation don't give enough informations or examples, but thanks anyway.

**Comment by claudiosanches** [comment]
@SkyNeT-ProD fell free to suggest changes and submit Pull Request, that I'll be happy to review and merge, thanks.
