### ISSUE TITLE
How to add products to a Grouped Product via API?

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-rest-api-docs#115]
Hi,

Have a user trying to do the following:

> I’m using the WooCommerce REST API v2 - I’m trying to create a group product and link some simple products to the group product. I can create the grouped product via the API successfully but can’t see how to link the child simple products to this grouped product? The API docs list the grouped_products element as ‘read only’ so not sure how this can be done via the API?

Is it possible at all? I can't seem to figure out how to do this, but wanted to check here as a last resort.

Here's the ticket for reference: 656846-zd-woothemes

Thanks!

**Comment by gedex** [comment]
Hi @zwiesman31,

I've tried locally to create a new grouped product and edit existing grouped product. Both work as expected, so I guess the doc needs to be updated to mark `grouped_products` property as editable (cc @claudiosanches). Here's an example to create a grouped product:

```
curl -X POST https://example.com/wp-json/wc/v2/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "name": "Test grouped product",
  "type": "grouped",
  "grouped_products": [1, 2, 3]
}'
```

where `[1, 2, 3]` is product IDs to be linked. It also possible to edit `grouped_products` of existing grouped product. For example:

```
curl -X PUT https://example.com/wp-json/wc/v2/products/4 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "grouped_products": [1, 2, 3]
}'
```

**Comment by claudiosanches** [comment]
Read-only in v1, but we fixed it on v2.
Docs updated now, thanks for report it.

**Comment by vitkoz** [comment]
It looks like it is back in v3. I get no errors but prod doesn't get set with the values
