### ISSUE TITLE
update categories attribute of a product

### ISSUE THREAD

**Issue by lexbryan** [woocommerce/woocommerce-rest-api-docs#117]
These are the categories for a product.

```
u'categories': [
    {u'slug': u'5m-16ft-pocket-tapes', u'id': 10301, u'name': u'5M - 16FT POCKET TAPES'}, 
    {u'slug': u'hand-tools', u'id': 10296, u'name': u'HAND TOOLS'}, 
    {u'slug': u'tapes-pocket-tapes', u'id': 10300, u'name': u'TAPES - POCKET TAPES'}, 
    {u'slug': u'tapes-rules', u'id': 10297, u'name': u'TAPES &amp; RULES'}, 
    {u'slug': u'trade-area', u'id': 10233, u'name': u'TRADE AREA'}]
```

I've been searching all over and can't find a reference how to remove a product from a category. I'm new to woocommerce and I hope someone can help. I read the api docs as well and can't find any.

api version: 2

Thank you in advance.

**Comment by claudiosanches** [comment]
Hello, for general support questions you should try https://wordpress.org/support/plugin/woocommerce

**Comment by lexbryan** [comment]
I'm using the rest-api.

**Comment by claudiosanches** [comment]
@lexbryan nice that you are using the REST API, but as I said, here is not a support channel, the correct place to ask for help is in https://wordpress.org/support/plugin/woocommerce
Thank you.
