### ISSUE TITLE
Update Slate?

### ISSUE THREAD

**Issue by michaeltieso** [woocommerce/woocommerce-rest-api-docs#126]
We're pretty far behind with Slate. Not sure what it would take to update. Is this something we want to do eventually?

**Comment by claudiosanches** [comment]
It's possible, still probably we'll lose some customization.
But there is any reason for we need update?

**Comment by michaeltieso** [comment]
I'm not sure. Is there anything new in the last couple years with Slate that would make this worth it? I haven't looked into it much. I only noticed that we were behind.
