### ISSUE TITLE
How can i do "add to cart" with woocommerce function in my api  ??

### ISSUE THREAD

**Issue by redsparkers** [woocommerce/woocommerce-rest-api-docs#128]
When i added the product from "WC()->cart->add_to_cart( $product_id );" but there is no user_id i am getting in the "wp_woocommerce_sessions" table
Check Refer- apiaddtocart.png
where first row when i add the item from website
and second row when i add the item from api
![apiaddtocart](https://user-images.githubusercontent.com/35765884/35729683-882f1142-0835-11e8-9d2c-66beffec47a6.png)

**Comment by claudiosanches** [comment]
Sorry, but this is not a support channel for the REST API.
This is for REST API documentation issue only.
