### ISSUE TITLE
Creating Coupon Files - invalid JSON?

### ISSUE THREAD

**Issue by wizardconsulting** [woocommerce/woocommerce-rest-api-docs#133]
I'm trying to add a coupon using the REST API. I'm getting connected fine, but keep getting an invalid JSON message. Not really sure where to go to ask about this, since I'm following the docs.

Here's the full cURLI'm passing:

`--header "Content-Type: application/json" -u (consumer_key):(consumer_secret) -d '{"code":"xxxxxxxxx", "discount_type":"fixed_cart", "amount":"100", "description":"Guest Referral for xxxxxxxx"}'`

I'm getting an HTTP response code of 400 and a JSON error code of 4.

Any help would be appreciated.

Thanks,
--
Michael Frankel
Wizard Consulting Group, Inc.

**Comment by claudiosanches** [comment]
This is not a support channel for WooCommerce REST API, please use the properly support channel, like https://wordpress.org/support/plugin/woocommerce or on WooCommerce.com. Thanks.
