### ISSUE TITLE
Weebhook for revoke of REST API authentication (revoke key under Advance tab / REST API)

### ISSUE THREAD

**Issue by aniruddhaad** [woocommerce/woocommerce-rest-api-docs#134]
I am trying to find a way to for -
Weebhook for revoke of REST API authentication (revoke key under Advance tab / REST API).

We need to know when someone revokes the KEY from their website admin WooCommerce settings > Advance tab > REST API link.

Is there any way to setup a webhook for this?

**Comment by claudiosanches** [comment]
Hi there. This repository is to reporting issues with REST API documentation, and it's not a WooCommerce support channel. Please submit this idea on WooCommerce repository.
