### ISSUE TITLE
typo in documentation for delete tag endpoint

### ISSUE THREAD

**Issue by stevelscott** [woocommerce/woocommerce-rest-api-docs#141]
http://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-product-tag

/wp-json/wc/v2/products/tag/<id>
should read:
/wp-json/wc/v2/products/**tags**/<id>

print(wcapi.delete("products/tag/34?force=true").json())
should read:
print(wcapi.delete("products/**tags**/34?force=true").json())

**Comment by claudiosanches** [comment]
Thanks for reporting it.
