### ISSUE TITLE
How can i get Products by specific category

### ISSUE THREAD

**Issue by ParthNandaniya** [woocommerce/woocommerce-rest-api-docs#143]
0
down vote
favorite
i tried all solution available on stackoverflow about filter products bycategory and i'm creating react native app and used node js, none of the are working.

`/products?filter[categories]=${item.name}${Constants.Keys}`
`/products?filter[category]=${item.name}${Constants.Keys}`
`/products?category=${item.name}${Constants.Keys}`

can somebody tell me how filter works on woocommerce REST API in node js or how can i get products by specific category??

**Comment by claudiosanches** [comment]
This repository is for the REST API documentation only, if you need help with the REST API, you could try https://wordpress.org/support/plugin/woocommerce
