### ISSUE TITLE
Couldnt Resolve Module Crypto From woocommerce-api

### ISSUE THREAD

**Issue by SMKH-PRO** [woocommerce/woocommerce-rest-api-docs#150]
woocommerce-api  uses a package "Crypto" which is now deprecated so this api isnt working in reactnative i am so stuck!... 

`error: bundling failed: Error: Unable to resolve module `crypto` from `C:\Users\SMKH\Desktop\ballpool\node_modules\woocommerce-api\index.js`: Module `crypto` does not exist in the Haste module map
`

Receiving this error because it is not installed and it cant be because it is deprecated but it is being used in woocommerce-api

**Comment by claudiosanches** [comment]
This is not a support channel for REST API libraries, please post in the library repository, thanks.
