### ISSUE TITLE
Incorrect type listed in documentation

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-rest-api-docs#157]
under https://woocommerce.github.io/woocommerce-rest-api-docs/#order-shipping-lines-properties

>total | string | Line total (after discounts).

but sending a string will result in a 400 response code.

**Comment by claudiosanches** [comment]
WooCommerce really uses string, see:

https://github.com/woocommerce/woocommerce-rest-api/blob/854ac947d84a3093a67af6714f11378990e1a916/src/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L1410-L1420

Maybe the error is from the legacy REST API endpoints.
