### ISSUE TITLE
Many 404s in the OAuth Tips of the Authentication over HTTPS area.

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-rest-api-docs#163]
The bottom of this page:

https://github.com/woocommerce/woocommerce-rest-api-docs/blob/master/source/includes/wp-api-v1/_authentication.md

![https://d.pr/i/Q5FkZv](https://d.pr/i/Q5FkZv+)
Image link: https://d.pr/i/Q5FkZv

**Comment by juliaamosova** [comment]
Thanks for reporting @tommyshellberg!
