### ISSUE TITLE
REST API source on Github - link is 404

### ISSUE THREAD

**Issue by mujuonly** [woocommerce/woocommerce-rest-api-docs#170]
https://github.com/woocommerce/woocommerce/tree/master/includes/api
![Screenshot 2020-02-18 at 1 47 21 PM](https://user-images.githubusercontent.com/459367/74716823-47e35500-5255-11ea-8f7a-4c25eb8e35cf.png)

**Comment by AndrewBarber** [comment]
Hey @mujuonly,
I've updated the link and the change has been merged.
