### ISSUE TITLE
Order Line items price type mismatch

### ISSUE THREAD

**Issue by Tarinu** [woocommerce/woocommerce-rest-api-docs#171]
In the [documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-line-items-properties) the type is marked as `string`.

In the examples, they're all `integer` (`3`, `9` and  `20`).

Looking at the [controller](https://github.com/woocommerce/woocommerce-rest-api/blob/c4c2fc64b55251d0f682767846570a356c1ca4f7/src/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L1297-L1301), it's marked as `number`.

Which one is the correct type then? Is it integer when it's a whole number and string when it's a decimal?

**Comment by claudiosanches** [comment]
We have updated a little our schema, updates on the docs should come soon too.
But you should use number, what is like a string, where you can use `10.99`.
