### ISSUE TITLE
Product's review list

### ISSUE THREAD

**Issue by invaders-xx** [woocommerce/woocommerce-rest-api-docs#173]
I use the api to get all the reviews list using 'status'='all' does not return all reviews : only approved and hold. Is it the expected result ?

Many thanks in advance,
David

**Comment by claudiosanches** [comment]
Hello, this repository is for the documentation only, if you have questions about the REST API you should try the forum: https://wordpress.org/support/plugin/woocommerce/
Or if you find a bug on WooCommerce: https://github.com/woocommerce/woocommerce/issues

Thanks!
