### ISSUE TITLE
X-WC-Webhook-Source update when updating domains?

### ISSUE THREAD

**Issue by surbhim13** [woocommerce/woocommerce-rest-api-docs#174]
It's more of a question rather than issue - 
Will X-WC-Webhook-Source get updated for future orders if http://example.com will move to http://example2.com by domain update by the user?

Reference for the header : 
https://woocommerce.github.io/woocommerce-rest-api-docs/?python#delivery-payload

**Comment by claudiosanches** [comment]
Hello, this repository is for the documentation only, if you have questions about the REST API you should try the forum: https://wordpress.org/support/plugin/woocommerce/
Or if you find a bug on WooCommerce: https://github.com/woocommerce/woocommerce/issues

Thanks!
