### ISSUE TITLE
How to apply filtering with multi values for each filter

### ISSUE THREAD

**Issue by rezalaki** [woocommerce/woocommerce-rest-api-docs#177]
Hi sir
I have almost read the [documents](https://woocommerce.github.io/woocommerce-rest-api-docs/) and I could not find my answer.
Is it possible to set multi value for single filter? If yes, how?
e.g. I have a cloth shop. I want to get products which have brand A, B and C.

**Comment by jnhghy** [comment]
Hello,
Depends under what parameter your values are if they are under attributes, try to specify them as a single string with the values separated by comma.

**Comment by claudiosanches** [comment]
Hello @rezalaki,

All parameters that accepts multiples values are listed as "array" in our documentation
You can see all in "Available parameters
" in https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
