### ISSUE TITLE
Get orders by meta data

### ISSUE THREAD

**Issue by jcasalins** [woocommerce/woocommerce-rest-api-docs#178]
Hello,

I have been looking in the documentation to obtain the orders by meta data, is it possible to carry out that search?
I tried using the "search" parameter, but it doesn't seem to search the meta data fields.

**Comment by claudiosanches** [comment]
Hello @Finalgamer14,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
