### ISSUE TITLE
Problems with webhooks

### ISSUE THREAD

**Issue by Finalgamer14** [woocommerce/woocommerce-rest-api-docs#182]
We are setting up a new store for a client, and working with outside company, to connect order update to their processing system.
We have a small problem, while the webhook gets created, as in when I input their URL and save it, it stays active, so I assume it can see the connection to the end point. But when an order happens or gets updated, the webhook gets disabled, when looking at logs it just says that the URL is incorrect (not that helpful ... like at all). When I POST a json file from the server using cURL I get HTTP/1.1 200 OK reply from their system, so I have no clue what the problem is for the webhook to disable it self.
Are we miss understanding how the system works, does WooCommerce webhook API expect more than just 200 OK reply?

**Comment by claudiosanches** [comment]
Hello @Finalgamer14,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
