### ISSUE TITLE
Woocommerce REST API Report

### ISSUE THREAD

**Issue by Tecommerce** [woocommerce/woocommerce-rest-api-docs#185]
Hello I saw this example in your guides:
<?php
$query = [
    'date_min' => '2016-05-03', 
    'date_max' => '2016-05-04'
];

print_r($woocommerce->get('reports/sales', $query));
?>

this is part of the result you have put in:
[
  {
    "total_sales": "14.00",
    "net_sales": "4.00",
    "average_sales": "2.00",
    "total_orders": 3,
    "total_items": 6,
    "total_tax": "0.00",
    "total_shipping": "10.00",
    "total_refunds": 0,
    "total_discount": "0.00",
    "totals_grouped_by": "day",
    "totals": {
      "2016-05-03": {
        "sales": "14.00",
        "orders": 3,
        "Items": 6,
        "tax": "0.00",
        "shipping": "10.00",
        "discount": "0.00",
        "customers: 0
      },

How to extract the value in totals->2016-05-03->sales?

Thank you very much

**Comment by Tecommerce** [comment]
does anyone know how to help me?

**Comment by claudiosanches** [comment]
Hello @Tecommerce,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
