### ISSUE TITLE
error 400 bad request

### ISSUE THREAD

**Issue by nariasoft** [woocommerce/woocommerce-rest-api-docs#61]
how to fix this error? 
this error only show on customer
 http://mydomain.org/index.php/wc-api/v3/customers/email/email@gmail.co…=1475246337&oauth_signature=LqRrSfz0hG3icL2BTuYRpLYZUjfDKTv6bGIawc1xJpU%3D

**Comment by claudiosmweb** [comment]
This is not a support channel.
If you need help with the REST API you should try https://wordpress.org/support/plugin/woocommerce
