### ISSUE TITLE
Webhook creation requires 'secret' field

### ISSUE THREAD

**Issue by colthreepv** [woocommerce/woocommerce-rest-api-docs#64]
Using WooCommerce 2.6.8, Wordpress 4.6.1 on Apache

Calling `/wp-json/wc/v1/webhooks` with basic-authentication with this payload:
```json
{
  "name": "Any name is valid",
  "topic": "product.created",
  "delivery_url": "http://requestb.in/tizasutj"
}
```

Returns a `400` response asking for a secret param.  
It's [stated in the documentation that's optional](https://github.com/woocommerce/woocommerce-rest-api-docs/blob/master/source/includes/v3/_webhooks.md#webhooks-properties), and will use the default user's consumer secret

**Comment by claudiosanches** [comment]
This is not option anymore, since have a key manager that allows users have more than one key.

And you are using the new WP REST API integration v1 and reading docs for our legacy API v3.

**Comment by claudiosanches** [comment]
Docs updated, thanks.

**Comment by colthreepv** [comment]
Thanks, yes I linked the wrong markdown :)
Nice support, keep it up
