### ISSUE TITLE
Product fee in Rest API

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce-rest-api-docs#65]
Hi,

Great plugin for product fees in woocommerce. How can we connect the Rest API in node?

I added product fee for 2 products. I want to know how we can pass keys in the node api for create order api

http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

Thanks
Basanth

**Comment by claudiosanches** [comment]
This is not a support channel, if found something wrong with the REST API docs feel free to start a issue here.
