### ISSUE TITLE
Coupons in Rest API

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce-rest-api-docs#68]
Hi,

I am using coupons rest api to get the discount in the create order.

Here is what i am passing to create order service
	"coupon_lines": [{
		"id":4334,
	   "code":"cstore",
	   "discount":5
	}],

After applying the code i am not getting the discount in order section in admin. Please suggest me what is wrong.

Thanks

**Comment by claudiosanches** [comment]
Sorry, but here it's not a channel for support.
