### ISSUE TITLE
Filter Products

### ISSUE THREAD

**Issue by VesperDev** [woocommerce/woocommerce-rest-api-docs#69]
Hi, how about I have a doubt to filter a serious product, when filter for example by name all very well

`    this.wooService.getProducts({ 'filter[name]' : 'Book Discount', }).then((products: Array<any>) => {
      
      console.log(products);
      this.products = products;
      

      this.loadingModal.dismiss();
    }, (reson) => {
      this.loadingModal.dismiss();
      this.errorModal.present();
    });
`

But for some strange reason when I write 'filter [on_sale]': 'true' does not search for products with that status

That I have to do to configure the search well, since when I look for po on_sale does not bring anything or there is another way to perform the searches

A greetings and thanks for your time

**Comment by claudiosanches** [comment]
Sorry but this repository is not for REST API support.
For support you can try https://wordpress.org/support/plugin/woocommerce

**Comment by VesperDev** [comment]
Thanks bro
