### ISSUE TITLE
Variation Properties Docs - Don't Mention "visible" Attribute

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce-rest-api-docs#72]
The Product Variations docs at:

http://woocommerce.github.io/woocommerce-rest-api-docs/#variation-properties

Don't mention the "visible" boolean type attribute that can be set for a variation (true/false). This is required to be set to for the variation to display as 'enabled' in the WordPress Admin screen.

**Comment by claudiosanches** [comment]
Just added, thanks for report it.
